#!/bin/zsh
setopt COMPLETE_ALIASES
alias E=' | egrep '
alias -g G=' | grep -i '
function specialchars(){echo '⇧⌘⌥⇥⌫⌦⎋⌃'}
function findalias(){
    for dir in $(echo ~/.dotFiles && echo $PATH | tr ':' '\n' | grep '^/Users/' | grep -v '\.nvm')
    do
       ack $1 $dir #ack is like grep, recursive by default, great option
    done
}
alias resetnpm='rm -rf ~/.npm && rm -rf node_modules && npm cache clear && npm i'
[[ -e /usr/local/bin/vim ]] && alias vim='/usr/local/bin/vim'
alias egrep='egrep --color=auto'
alias setbash='chsh -s /bin/bash'
alias reload='. ~/.zshrc'
# alias grep='egrep'
alias ls='ls -GF1'
alias updatedb='sudo /usr/libexec/locate.updatedb' #for locate's sake
alias opengabi='cd ~/Developer/selenium/criancas/selenium && jasmine spec/escola.spec.js gabi'
alias hidden='ls -d .*'
alias restart='sudo shutdown -r now'
alias textedit='open -a TextEdit'
alias lockscreen='pmset displaysleepnow'
alias mongod='mongod --dbpath ~/Dropbox/Mongodb/data24'

alias pdf2jpeg='echo "enter filename : " && read MSG && sips -s format jpeg "$MSG".pdf --out "$MSG".jpeg'

alias startitsmylife='osascript ~/Developer/ItsMyLife/start_Mongod_Nodemon_Watch.scpt'

#GIT STUFF
alias gacp='echo "enter commit message : " && read MSG && git add . && git commit -m "$MSG" && git push'
alias gmdc='git merge --no-commit --no-ff'

alias open8080='open http://localhost:8080'
