#!/bin/zsh
setopt COMPLETE_ALIASES
# alias vim='nvim'
alias -g E=' | egrep '
alias -g G=' | grep -i '
#we pipe overwrite '>' to a file instead of openning it derectly in vim '| vim -'
#because we want to exit ZZ 
alias -g V=' > ~/.vim-tmp/t && vim ~/.vim-tmp/t -c '\''nmap q :q!<cr>'\'
# git status in vim. Due to our vim setup, "map ,d" opens diff in webstorm. also all vim-fugitive stuff work
alias -g ME='--author=davidsu'
alias -g NO='--name-only'
alias -g M='--max-count=100'
alias gsv='vim -c '\''source $DOTFILES/vim/startup/gitstatus'\'' $(git rev-parse --show-toplevel)/.git/index'
# git log in vim. Limit to last 500 commits otherwise its pretty slow.
alias glv='git log --max-count=500 --name-only V'
function specialchars(){echo '⇧⌘⌥⇥⌫⌦⎋⌃'}
function findalias(){
    for dir in $(echo ~/.dotFiles && echo $PATH | tr ':' '\n' | grep '^/Users/' | grep -v '\.nvm')
    do
       ack $1 $dir #ack is like grep, recursive by default, great option
    done
}
alias resetnpm='rm -rf ~/.npm && rm -rf node_modules && npm cache clear && npm i'
alias vim='nvim'
alias egrep='egrep --color=auto'
alias setbash='chsh -s /bin/bash'
alias reload='. ~/.zshrc'
# alias grep='egrep'
alias ls='ls -GF1'
alias updatedb='sudo /usr/libexec/locate.updatedb' #for locate's sake
alias opengabi='cd ~/Developer/selenium/criancas/selenium && jasmine spec/escola.spec.js gabi'
alias hidden='ls -d .*'
alias restart='sudo shutdown -r now'
alias textedit='open -a TextEdit'
alias lockscreen='pmset displaysleepnow'
alias mongod='mongod --dbpath ~/Dropbox/Mongodb/data24'

alias pdf2jpeg='echo "enter filename : " && read MSG && sips -s format jpeg "$MSG".pdf --out "$MSG".jpeg'

alias startitsmylife='osascript ~/Developer/ItsMyLife/start_Mongod_Nodemon_Watch.scpt'

#GIT STUFF
alias gacp='echo "enter commit message : " && read MSG && git add . && git commit -m "$MSG" && git push'
alias gmdc='git merge --no-commit --no-ff'

alias open8080='open http://localhost:8080'
