#!/bin/sh
  ###########################################################################################################################
  #SET COLORS IN MAN PAGES
  PAGER='less -ij5Q'
  export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
  export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
  export LESS_TERMCAP_me=$'\E[0m'           # end mode
  # export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
  # export LESS_TERMCAP_so=$'\E[38;33;246m'   # begin standout-mode - info box
  export LESS_TERMCAP_ue=$'\E[0m'           # end underline
  export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

  export LESS='-Ri'       #reasonable less flags
  export MANPAGER="nvim -u $HOME/.config/nvim/init_for_man.vim -c 'set ft=man' -"

  # export LESS_TERMCAP_so=$'\E[01;37;04;41m'
  ###########################################################################################################################
