#!/bin/zsh
function loadzgen(){
    source $DOTFILES/theme

    source ~/.zgen/zgen.zsh
    if ! zgen saved; then
        zgen oh-my-zsh
        zgen load zsh-users/zsh-syntax-highlighting
        zgen load zsh-users/zsh-history-substring-search
        zgen oh-my-zsh plugins/git
        zgen oh-my-zsh plugins/yarn
        zgen load paulirish/git-open
    fi
    #unset SET_CUSTOM_PROMPT value if you want to test other prompt than
    #the custom in ~/.dotFiles/prompt
    SET_CUSTOM_PROMPT=true
    #fix prompt but also fix back my options that oh-my-zsh fucks up, e.g:ls output style
    [[ -n $reloadforzgen ]] && reload
    #we need to re-source fzf here otherwise oh-my-zsh overwrites its bindings!!!
    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}
reloadforzgen=1
function loadrvm(){
    export PATH="$PATH:$HOME/.rvm/bin:$HOME/.bin" # Add RVM to PATH for scripting
    # echo "loading rvm"
    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
}
function nvm_auto_switch {
    #stolen from https://github.com/dijitalmunky/nvm-auto

    [[ $skipnvm -eq 1 ]] && return
    unset NVM_RC_VERSION
    CUR_VERSION=$(node -v |cut -c 2)
    nvm_rc_version > /dev/null 2>&1

    if [ -z "${NVM_RC_VERSION}" ]
    then
        export NVM_RC_VERSION=$(nvm_version default | cut -c 2)
    else
        NVM_RC_VERSION=$( cut -c 1 <<< $NVM_RC_VERSION ) 
    fi

    if [ $NVM_RC_VERSION != $CUR_VERSION ]
    then
        echo nvmrcversion: $NVM_RC_VERSION
        echo curversion: $CUR_VERSION
        echo changing node version to $NVM_RC_VERSION
        nvm use >/dev/null 2>&1 || nvm use default >/dev/null 2>&1
    fi
}
function loadnvm(){
    export NVM_DIR="$HOME/.nvm"
    [ -s "${NVM_BREW_PREFIX}/nvm.sh" ] && . "${NVM_BREW_PREFIX}/nvm.sh"
    export NVM_NODEJS_ORG_MIRROR=http://nodejs.org/dist

    autoload -U add-zsh-hook
    add-zsh-hook chpwd nvm_auto_switch
    #change node version iff .nvmrc in pwd
    # if [[ -f .nvmrc ]]; then
    #     nvm use
    # else
    #     # use nvm node if not using it already
    #     if [[ $(type node) =~ 'not found' ]] || [[ ! $(which node) =~ '/.nvm/' ]]; then
    #         nvm use 8
    #     fi
    # fi
}
function loadnvmAutocomplete(){
    [ -s "${NVM_BREW_PREFIX}/etc/bash_completion.d/nvm" ] && . "${NVM_BREW_PREFIX}/etc/bash_completion.d/nvm"
}
function load(){
    export HAS_LOADED=1  
    reloadforzgen=''
    loadzgen
    reloadforzgen=1
    loadrvm
    reload
}
function loadall(){
    export HAS_LOADED=1  
    if [[ $NVM_BREW_PREFIX == '' ]]; then
        export NVM_BREW_PREFIX=$(cat /tmp/brew_prefix_nvm)
    fi
    reloadforzgen=''
    loadzgen
    reloadforzgen=1
    loadrvm
    loadnvm
    loadnvmAutocomplete
    # rvm complains about not being first in path
    PATH=$(echo $PATH | tr ':' '\n' | uniq | tr '\n' ':')
    reload
    cd ./
}
if [[ -z $loadallsourced ]]; then
    alias l='load'
    alias l!='loadall'
    alias lnvm='loadnvm && loadnvmAutocomplete && cd ./'
    alias lall='loadall'
    loadallsourced=1
fi



#this doesn't seem to work here... need to learn more
ZDOTDIR='~/.dotFiles/zsh'
# completion
autoload -U compinit
compinit
# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending
zstyle ':completion:*' verbose yes #pg 96 =>Learning Shell Scripting with ZSH
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='fg=red,bold' # zsh-users/zsh-history-substring-search highlight match
#bindkey -v #set "key schema" to vi mode, improved with plugins/vi-mode...WORKS GREAT


export LSCOLORS=GxFxCxDxBxegedabagaced #better colors for ls

autoload zmv # => pg 88 Learning Shell scripting with ZSH
setopt HIST_VERIFY # !! => copy cmd from history before executing
