#!/bin/sh
function loadzgen(){
    source $DOTFILES/theme

    source ~/.zgen/zgen.zsh
    if ! zgen saved; then
        zgen oh-my-zsh
        zgen load zsh-users/zsh-syntax-highlighting
        zgen load zsh-users/zsh-history-substring-search
        zgen oh-my-zsh plugins/git
        # zgen oh-my-zsh plugins/vi-mode
        # zgen load wting/autojump
    fi
    #unset SET_CUSTOM_PROMPT value if you want to test other prompt than
    #the custom in ~/.dotFiles/prompt
    SET_CUSTOM_PROMPT=true
    #fix prompt but also fix back my options that oh-my-zsh fucks up, e.g:ls output style
    reload
    #we need to re-source fzf here otherwise oh-my-zsh overwrites its bindings!!!
    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
}
function loadrvm(){
    export PATH="$PATH:$HOME/.rvm/bin:$HOME/.bin" # Add RVM to PATH for scripting
    # echo "loading rvm"
    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
}
function loadnvm(){
    l=`alias ln`
    if [ -n $l ]; then; 
        unalias ln
    fi
    export NVM_DIR="$HOME/.nvm"
    [ -s "$(brew --prefix nvm)/nvm.sh" ] && . "$(brew --prefix nvm)/nvm.sh"
    export NVM_NODEJS_ORG_MIRROR=http://nodejs.org/dist

    autoload -U add-zsh-hook
    load-nvmrc() {
      if [[ -f .nvmrc && -r .nvmrc ]]; then
        nvm use
      fi
    }
    add-zsh-hook chpwd load-nvmrc
}
function loadnvmAutocomplete(){
    [ -s "$(brew --prefix nvm)/etc/bash_completion.d/nvm" ] && . "$(brew --prefix nvm)/etc/bash_completion.d/nvm"
}
function loadall(){
    unalias l
    loadzgen
    loadrvm
    loadnvm
    loadnvmAutocomplete
    # rvm complains about not being first in path
    PATH=$(echo $PATH | tr ':' '\n' | uniq | tr '\n' ':')
    reload
}

alias lz='loadzgen'
alias lr='loadrvm'
alias ln='loadnvm'
l=`alias l`
if [ -z $l ]; then; 
    #here we cd ./ to give nvmrc a chance to kick in
    alias l='loadall; reload; cd ./'
fi




#this doesn't seem to work here... need to learn more
ZDOTDIR='~/.dotFiles/zsh'
# completion
autoload -U compinit
compinit
# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending
zstyle ':completion:*' verbose yes #pg 96 =>Learning Shell Scripting with ZSH
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='fg=red,bold' # zsh-users/zsh-history-substring-search highlight match
#bindkey -v #set "key schema" to vi mode, improved with plugins/vi-mode...WORKS GREAT


export LSCOLORS=GxFxCxDxBxegedabagaced #better colors for ls

autoload zmv # => pg 88 Learning Shell scripting with ZSH
setopt HIST_VERIFY # !! => copy cmd from history before executing
