#!/bin/zsh
hash -d d=~/.dotfiles/
j() {
    if [ $(hash -d|cut -d= -f1|grep -c "^$1\$") = 0 ]; then
	fasd_cd -d "$@"
    else
	cd ~$1
    fi
}
function pullMyProjects(){
    skipnvm=1
    pullIfMineAndNotDirty() {
        if [[ $(git config --get remote.origin.url) =~ 'sudavid4' ]]; then
	    echo "\033[38;5;6m"$(pwd)"\033[0m"
            if [[ $(git diff --shortstat 2> /dev/null | tail -n1) == "" ]]; then
                git pull
            else
                echo "\033[38;5;9m"---------------IS DIRTY--------------------------"\033[0m"
            fi
        fi
    }
    scan () {
        curdir=$(pwd)
        for x in $*
        do
            [[ -d $x ]] && [[ -d ${x}/.git ]] && cd $x &> /dev/null && pullIfMineAndNotDirty "$x" 2> /dev/null
            cd $curdir &> /dev/null
        done
    }
    scan * 
    wait
    skipnvm=0
}

function encrypt(){
	if [ -f $1 ]; then
		openssl des -k ohencrypted -in $1 -out $1.enc && rm $1
	else
		echo no such file $1
	fi
}
function decrypt(){
	if [ -f $1 ]; then
		decfilename=${1%.enc}
        openssl des -d -k ohencrypted -in $decfilename.enc -out $decfilename && rm $1
    else
		echo no such file $1
	fi
}

function encryptdir(){
	if [ -d $1 ]; then
		for f in $1*; do
			encrypt $f
		done
	else
		echo no such directory $1
	fi

}

function decryptdir(){
	if [ -d $1 ]; then
		for f in $1*; do
			decrypt $f
		done
	else
		echo no such directory $1
	fi

}
function dirtyprojs(){
    skipnvm=1
    function printdirty {
        local d="$1"
        [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]] && echo $(pwd);
    }

    function scan {
        curdir=$(pwd)
        for x in $*; do
            [[ -d $x ]] && [[ -d ${x}/.git ]] && cd $x &> /dev/null && printdirty "$x" 2> /dev/null; cd $curdir &> /dev/null  
        done
    }
    scan * | grep -v 'running nvm' | grep '^/User.*'
    wait
    skipnvm=0
}
function escape_ls(){
  for COLOR in {0..255}
  do
    for STYLE in "38;5"
    do
      TAG="\033[${STYLE};${COLOR}m"
      STR="${STYLE};${COLOR}"
      echo -n "${TAG}"'\\033['"${STR}"'m'"${NONE}  "
    done
    echo
  done
}
function createTernProj(){
    echo '
{
  "ecmaVersion": 8,
  "libs": [
      "browser",
      "ecma6"
  ],
  "plugins": {
    "node": {},
    "modules": {},
    "es_modules": {},
    "node_resolve": {},
    "CommonJS": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}' > .tern-project
}
for f in $DOTFILES/cheatSheets/*
do
    if [[ -f $f ]]; then
        alias cheat$(basename $f)='cat '$f' | fzf'
    fi
done
