#!/bin/sh
#if we run twice the following code we create an infinite loop
if [[ -z $joverloaded ]]; then
    save_function() {
        local ORIG_FUNC=$(declare -f $1)
        local NEWNAME_FUNC="$2${ORIG_FUNC#$1}"
        eval "$NEWNAME_FUNC"
    }
    save_function j originalJ
    #original autojump `j` function doesn't take hashed dir into account. fixing it
    j() {
        if [ $(hash -d|cut -d= -f1|grep -c "^$1\$") = 0 ]; then
            echo originalj
            originalJ "$@"
        else
            cd ~$1
        fi
    }
fi
joverloaded=1
