#!/bin/zsh
if [[ $SET_CUSTOM_PROMPT == "true" ]]; then
    # Outputs current branch info in prompt format
      function my_git_prompt_info() {
       local ref
       if [[ "$(command git config --get oh-my-zsh.hide-status 2>/dev/null)" != "1" ]]; then
         ref=$(command git symbolic-ref HEAD 2> /dev/null) || \
         ref=$(command git rev-parse --short HEAD 2> /dev/null) || return 0
         echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/} $(git_prompt_status)$ZSH_THEME_GIT_PROMPT_SUFFIX"
       fi
     }

     function color_for_most_used_dirs() {
       if [[ $(pwd) =~ .*santa-edi.* ]]; then
        echo "%{[38;5;101m%}"
      elif [[ $(pwd) =~ .*santa.* ]]; then
        echo "%{[38;5;67m%}"
      elif [[ $(pwd) =~ .*wix-ck-ed.* ]]; then
        echo "%{[38;5;131m%}"
      else
        echo "%{$reset_color%}"
      fi
     }

    local ret_status="%(?:%{$fg[green]%}➜ :%{$fg_bold[red]%}➜%s)"
    PROMPT='${ret_status}%{$fg_bold[green]%}%p $(color_for_most_used_dirs)%3~ $(my_git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'

    ZSH_THEME_GIT_PROMPT_PREFIX="%{$reset_color%}( %{$fg[blue]%}"
    ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}) "

    ZSH_THEME_GIT_PROMPT_ADDED="%{$fg[yellow]%}✚ "
    ZSH_THEME_GIT_PROMPT_MODIFIED="%{$fg[green]%}✭ "
    ZSH_THEME_GIT_PROMPT_DELETED="%{$fg[red]%}✗ "
    ZSH_THEME_GIT_PROMPT_RENAMED="%{$fg[blue]%}➦ "
    ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[magenta]%}✂ "
    ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[cyan]%}✱ "
    function git_prompt(){
        local str=$2 #local limits str variable scope
        echo -n $1 | sed 's/%{\(.*\)%}.*/\1/g' #color
        echo -n "$2 " #name of status
        echo -n "$(printf '\055%.0s' {1..20})" | head -c $(( 20 - ${#str} )) #dashes
        echo -n $1 | sed 's/%{\(.*\)%}/ \1/g' #character that represents it
    }
    function gitprompt(){
        function git_prompt(){
            local str=$2 #local limits str variable scope
            echo -n $1 | sed 's/%{\(.*\)%}.*/\1/g' #color
            echo -n "$2 " #name of status
            echo -n "$(printf '\055%.0s' {1..20})" | head -c $(( 20 - ${#str} )) #dashes
            echo -n $1 | sed 's/%{\(.*\)%}/ \1/g' #character that represents it
        }
        git_prompt $ZSH_THEME_GIT_PROMPT_ADDED added
        git_prompt $ZSH_THEME_GIT_PROMPT_MODIFIED modified
        git_prompt $ZSH_THEME_GIT_PROMPT_DELETED deleted
        git_prompt $ZSH_THEME_GIT_PROMPT_RENAMED renamed
        git_prompt $ZSH_THEME_GIT_PROMPT_UNMERGED unmerged
        git_prompt $ZSH_THEME_GIT_PROMPT_UNTRACKED untracked
        unset -f git_prompt #keep global namespace clean
    }
fi
