#!/bin/sh
_nicethemes=(
'base16-3024'
'base16-chalk'
'base16-darktooth'
'base16-default-dark'
'base16-eighties'
'base16-embers'
'base16-hopscotch'
'base16-pico'
'base16-pop'
)
function themes(){
	for i in `seq 1 ${#_nicethemes}`; do
		printf "%s\t%s\n" "$i" "${_nicethemes[$i]}"
	done
}
function changetheme(){
	echo $1
	#local idx=$(( $1 % ${#_nicethemes[@]} ))
	local idx=$1
	THEME=${_nicethemes[idx]}
	echo "changing theme to: $THEME:u" #:u is zsh's toUpperCase
	source "$DOTFILES/.config/base16-shell/scripts/$THEME.sh"
}
