#!/bin/zsh
function serveeditor()(
    loadallifneeded
    cd ~/projects/tools/wm-local-http-static-server
    sudo -b npm start
)
function killeditor(){
    #kill with SIGINT=2 by default
    signal=${1:-2}
    echo killing with signal $signal
    sudo kill -$signal $(sudo lsof -i tcp:80 -t)
    sudo kill -$signal $(sudo lsof -i tcp:443 -t)
}

function deepuicheckout () {
    if [[ $# != 1 ]]; then
        echo 'usage: deepuicheckout $desired_branch'
        return 1
    fi
	for dir in ~/deepui/*
	do
		echo $dir
		cd $dir
        if [[ $(git diff --shortstat 2> /dev/null | tail -n1) == "" ]]; then
            git reset --hard
            git pull
            git checkout $1
            npm i
        else
            echo "\033[38;5;196m"$(pwd) is dirty, refusing to continue "\033[0m"
        fi
	done
}
function deepuistart() {
    loadallifneeded
    pg_isready || pg_ctl -D /usr/local/var/postgres start
    cd ~/deepui/end-user/
    echo 'yarn dev --> '$(pwd) 
    nohup yarn dev &> /tmp/deepui-end-user &

    cd ~/deepui/web-server/
    echo 'yarn dev --> ' $(pwd)
    nohup yarn dev &> /tmp/deepui-web-server < /dev/null &

    cd ~/deepui/automaton-executor/
    echo 'yarn dev --> ' $(pwd)
    nohup yarn dev &> /tmp/deepui-automaton-executor &

    cd ~/deepui/automaton-processor/
    echo 'yarn start --> ' $(pwd)
    nohup yarn start &> /tmp/deepui-automaton-processor &
}
alias showdeepuiprocessor='tail -f /tmp/deepui-automaton-processor'
alias showdeepuiexecutor='tail -f /tmp/deepui-automaton-executor'
alias showdeepuiserver='tail -f /tmp/deepui-web-server'
alias showdeepuienduser='tail -f /tmp/deepui-end-user'

alias nolocal='[[ -f ~/walkme/settings.json ]] && mv ~/walkme/settings.json ~/walkme/_settings.json'
alias setlocal='[[ -f ~/walkme/_settings.json ]] && mv ~/walkme/_settings.json ~/walkme/settings.json'
