#!/bin/sh
export CK="$HOME/projects/wix-ck-editor/"
export SV="$HOME/projects/santa/"
export SE="$HOME/projects/santa-editor/"
export WR="$HOME/projects/wix-richtext/"
export CODE_SDK="$HOME/projects/js-wixcode-sdk/"
#https://www.youtube.com/watch?v=FWIZhzy-RJs
hash -d a=~/projects/santa/
hash -d e=~/projects/santa-editor/
hash -d c=~/projects/wix-ck-editor/
hash -d r=~/projects/wix-richtext/
hash -d me=~/projects/santa-members/santa-members-editor-app/
alias whokilledsanta='open http://santa.wixpress.com'
alias killsanta='sudo kill -9 `sudo lsof -i tcp:80 -t`'
#teamcity uses same username+password as in your computer
alias openteamcitysantaeditor='open '\''http://tc.dev.wixpress.com/viewType.html?buildTypeId=Santa_SantaEditor'\'
alias openteamcitysantaviewer='open '\''http://tc.dev.wixpress.com/viewType.html?buildTypeId=HtmlClient_Reactum'\'
alias openteamcitywixrichtext='open http://tc.dev.wixpress.com/viewType.html?buildTypeId=WixRichtext_WixRichtext&tab=buildTypeStatusDiv'
alias openteamcitypullrequestsantaviewer='open https://pullrequest-tc.dev.wixpress.com/project.html?projectId=Santa&tab=projectOverview'
alias openeditorcurrent='open '\''http://editor.wix.com/html/editor/web/renderer/edit/1fa8b8b7-9cc5-4472-801a-6e14b3a667c7?metaSiteId=80176187-9bac-4cab-9ddc-f700c9e45445&editorSessionId=427C0A90-6DBB-4B6C-B3A1-27A91A1099FF&experiments=sv_dpages%2CdisableDbEditorAutoSave%2CdisableSaveReminder%2CrightClickDebug%2Cdpages%2Cse_platform1%2Csv_platform1%2CfastStyling%2Cse_grid%2Csv_grid%2CdeveloperModeToggle&editorPlatformAppSources=%3A&viewerPlatformAppSources=%3A&WixCodeRuntimeSource=1.2264.0&EditorSource=http%3A%2F%2Flocalhost%2Feditor-base&debug=all&ReactSource=http%3A%2F%2Flocalhost&petri_ovr=specs.EnableNewRelicInSanta%3Afalse%3Bspecs.DisableNewRelicScriptsSantaEditor%3Atrue%3Bspecs.HttpsAllowedForPremiumSites%3Afalse%3Bspecs.HttpsAllowedForFreeSites%3Afalse&leavePagePopUp=false'\'
alias openviewercurrent='open '\''http://davidsu9.wixsite.com/customrouter?EditorSource=http%3A%2F%2Flocalhost%2Feditor-base&ReactSource=http%3A%2F%2Flocalhost&WixCodeRuntimeSource=1.2244.0&editorPlatformAppSources=%3A&experiments=disableDbEditorAutoSave%2CdisableSaveReminder%2CrightClickDebug%2Cdpages%2Csv_dpages%2Cse_platform1%2Csv_platform1%2CfastStyling%2Cse_grid%2Csv_grid%2CdeveloperModeToggle&petri_ovr=specs.EnableNewRelicInSanta%3Afalse%3Bspecs.DisableNewRelicScriptsSantaEditor%3Atrue%3Bspecs.HttpsAllowedForPremiumSites%3Afalse%3Bspecs.HttpsAllowedForFreeSites%3Afalse&debug=all&viewerPlatformAppSources=%3A'\'
function servesanta(){
   cd ~/projects/santa
   sudo -b npm start
}
function openeditormembersarea(){
   cd /Users/davidsu/projects
   serve-https &
   # open 'http://editor.wix.com/html/editor/web/renderer/new?siteId=cbf36d3a-49d0-41c2-9482-1bb58d5fdda3&metaSiteId=a573279f-ae6f-46d1-8556-7c93ae9b2c84&editorSessionId=B67E3913-423B-4C73-A9A3-C38C8A991270&editorPlatformAppSources=members-application:1.4.0&viewerPlatformAppSources=members-application:1.4.0&debug=all&experiments=se_santaMembers,sv_santaMembers&ReactSource=http://localhost&EditorSource=http://localhost/editor-base&petri_ovr=specs.EnableNewRelicInSanta:false;specs.DisableNewRelicScriptsSantaEditor:true;specs.HttpsAllowedForPremiumSites:false;specs.HttpsAllowedForFreeSites:false'
   open 'http://editor.wix.com/html/editor/web/renderer/edit/f8a89db9-4c69-4e40-834e-99e811fc2fce?metaSiteId=534248d8-f7f3-4187-a782-aee081e408bc&editorSessionId=16643624-A19C-46DC-82B2-EAD4DF6AE31A&EditorSource=http://localhost/editor-base&ReactSource=http://localhost&editorSdkSource=http://localhost/editor-sdk/build/editorSDK.js&PlatformContainerSource=http://localhost/platform-apps-container&debug=all&editorPlatformAppSources=members-application:1.4.0&experiments=disableDbEditorAutoSave,disableSaveReminder,se_santaMembers,sv_santaMembers&petri_ovr=specs.EnableNewRelicInSanta:false;specs.DisableNewRelicScriptsSantaEditor:true;specs.HttpsAllowedForPremiumSites:false;specs.HttpsAllowedForFreeSites:false&viewerPlatformAppSources=members-application:1.4.0&leavePagePopUp=false&hot=false'
}
function openviewermembersarea(){
    cd /Users/davidsu/projects
    serve-https &
    open 'http://davidsu9.wixsite.com/membersarea?EditorSource=http%3A%2F%2Flocalhost%2Feditor-base&ReactSource=http%3A%2F%2Flocalhost&WixCodeRuntimeSource=1.2335.0&debug=all&editorPlatformAppSources=members-application%3A1.4.0&editorSessionId=771DFA69-D9CE-469A-8DC0-FE47E3BAD95A&experiments=disableDbEditorAutoSave%2CdisableSaveReminder%2CrightClickDebug%2Cdpages%2Csv_dpages%2Cse_platform1%2Csv_platform1%2CfastStyling%2Cse_grid%2Csv_grid%2CdeveloperModeToggle%2Cse_santaMembers%2Csv_santaMembers&leavePagePopUp=false&metaSiteId=32f2979d-5c96-4b85-973c-df62b11afc51&petri_ovr=specs.EnableNewRelicInSanta%3Afalse%3Bspecs.DisableNewRelicScriptsSantaEditor%3Atrue%3Bspecs.HttpsAllowedForPremiumSites%3Afalse%3Bspecs.HttpsAllowedForFreeSites%3Afalse&viewerPlatformAppSources=members-application%3A1.4.0&leavePagePopUp=false'
}
function openeditormembersareablank(){
   cd /Users/davidsu/projects
   serve-https &
   open 'http://editor.wix.com/html/editor/web/renderer/edit/a9ab470f-d936-4fde-a076-328737e46b43?EditorSource=http%3A%2F%2Flocalhost%2Feditor-base&ReactSource=http%3A%2F%2Flocalhost&WixCodeRuntimeSource=1.2335.0&debug=all&editorPlatformAppSources=members-application%3A1.4.0&editorSessionId=771DFA69-D9CE-469A-8DC0-FE47E3BAD95A&experiments=disableDbEditorAutoSave%2CdisableSaveReminder%2CrightClickDebug%2Cdpages%2Csv_dpages%2Cse_platform1%2Csv_platform1%2CfastStyling%2Cse_grid%2Csv_grid%2CdeveloperModeToggle%2Cse_santaMembers%2Csv_santaMembers&leavePagePopUp=false&metaSiteId=32f2979d-5c96-4b85-973c-df62b11afc51&petri_ovr=specs.EnableNewRelicInSanta%3Afalse%3Bspecs.DisableNewRelicScriptsSantaEditor%3Atrue%3Bspecs.HttpsAllowedForPremiumSites%3Afalse%3Bspecs.HttpsAllowedForFreeSites%3Afalse&viewerPlatformAppSources=members-application%3A1.4.0&leavePagePopUp=false&hot=false'
}
function startdynamic(){
    (#parentheses causes code to be run in subshell
        trap "kill $(jobs -p)" SIGINT SIGTERM EXIT
        node $SV/beaker/dynamicPages/backend.js &
        cd $SV
        sudo npm start
    )
   wait
}
function startwixrichtextday(){
   {
      cd $WR &&
      git pull &&
      npm i
   }
}
function startsantaday(){
    {
        cd $SV &&
        git pull --rebase &&
        npm  i &&
        grunt all --force &&
        node tern_proj_generator `pwd`/packages > .tern-project
     } | egrep -v $LOG
}
function startsantaeditorday(){
    {
        cd ~/projects/santa-editor &&
        git pull --rebase &&
        npm i &&
        bower install --force &&
        grunt all --force &&
        node tern_proj_generator `pwd`/packages > .tern-project
    } | egrep -v $LOG
}
function startckday(){
    cd ~/projects/wix-ck-editor &&
    git pull --rebase &&
    bower update &&
    grunt all
}
function startwixcodeday(){
    cd ~/projects/js-wixcode-sdk &&
    git pull --rebase &&
    npm i &&
    grunt all &&
    npm run build &&
    cd ~/projects/santa/static/wixcode &&
    grunt &&
    cd ~/projects/santa/static/platform &&
    grunt

}
function startwixday(){
#command inside ( parenthesis ) will be run in a subshell
#allowing for parallelism
    ( startsantaday ) &
    ( startsantaeditorday ) &
    ( startckday ) &
    ( startwixrichtextday ) &
    ( startwixcodeday )
}
function notonmaster(){
    local pwd=$PWD
    cd $SV
    local currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $SE
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $CK
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $CODE_SDK
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $pwd
}
function checkoutmasterfunc(){
    cd $1
    echo $fg[yellow]$PWD$reset_color
    git checkout master
    printf '*%.0s' {1..50}
    printf '\n\n'
}
alias checkoutmaster='checkoutmasterfunc ~/projects/wix-ck-editor && checkoutmasterfunc ~/projects/santa && checkoutmasterfunc ~/projects/santa-editor && checkoutmasterfunc ~/projects/js-wixcode-sdk'
