#!/bin/sh
WIX_CK="$HOME/projects/wix-ck-editor/"
WIX_SV="$HOME/projects/santa/"
WIX_SE="$HOME/projects/santa-editor/"
WIX_CODE_SDK="$HOME/projects/js-wixcode-sdk/"

function startdynamic(){
    (#parentheses causes code to be run in subshell
        trap "kill $(jobs -p)" SIGINT SIGTERM EXIT
        node $WIX_SV/beaker/dynamicPages/backend.js &
        cd $WIX_SV
        sudo npm start
    )
   wait
}
function startsantaday(){
    {
        cd $WIX_SV &&
        git pull &&
        npm  i &&
        grunt all --force
    } | egrep -v $LOG
}
function startsantaeditorday(){
    {
        cd ~/projects/santa-editor &&
        git pull &&
        npm i &&
        grunt all --force
    } | egrep -v $LOG
}
function startckday(){
    cd ~/projects/wix-ck-editor &&
    git pull &&
    bower update &&
    grunt all
}
function startwixcodeday(){
    cd ~/projects/js-wixcode-sdk &&
    git pull &&
    npm i &&
    grunt all &&
    npm run build &&
    cd ~/projects/santa/static/wixcode &&
    grunt
}
function startwixday(){
#command inside ( parenthesis ) will be run in a subshell
#allowing for parallelism
    ( startsantaday ) &
    ( startsantaeditorday ) &
    ( startckday ) &
    ( startwixcodeday )
}
function notonmaster(){
    local pwd=$PWD
    cd $WIX_SV
    local currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $WIX_SE
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $WIX_CK
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $WIX_CODE_SDK
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $pwd
}
function checkoutmasterfunc(){
    cd $1
    echo $fg[yellow]$PWD$reset_color
    git checkout master
    printf '*%.0s' {1..50}
    printf '\n\n'
}
alias checkoutmaster='checkoutmasterfunc ~/projects/wix-ck-editor && checkoutmasterfunc ~/projects/santa && checkoutmasterfunc ~/projects/santa-editor && checkoutmasterfunc ~/projects/js-wixcode-sdk'
