#!/bin/sh
export CK="$HOME/projects/wix-ck-editor/"
export SV="$HOME/projects/santa/"
export SE="$HOME/projects/santa-editor/"
export WR="$HOME/projects/wix-richtext/"
export CODE_SDK="$HOME/projects/js-wixcode-sdk/"

alias whokilledsanta='open http://santa.wixpress.com'
alias killsanta='echo you need to sudo something before this && sudo kill -9 `sudo lsof -i tcp:80 -t`'
#teamcity uses same username+password as in your computer
alias openteamcitysantaeditor='open http://tc.dev.wixpress.com/viewType.html?buildTypeId=Santa_SantaEditor'
alias openteamcitysantaviewer='open http://tc.dev.wixpress.com/viewType.html?buildTypeId=HtmlClient_Reactum'
alias openteamcitywixrichtext='open http://tc.dev.wixpress.com/viewType.html?buildTypeId=WixRichtext_WixRichtext&tab=buildTypeStatusDiv'
alias openeditorcurrent='open '\''http://editor.wix.com/html/editor/web/renderer/edit/1fa8b8b7-9cc5-4472-801a-6e14b3a667c7?metaSiteId=80176187-9bac-4cab-9ddc-f700c9e45445&editorSessionId=427C0A90-6DBB-4B6C-B3A1-27A91A1099FF&experiments=disableDbEditorAutoSave%2CdisableSaveReminder%2CrightClickDebug%2Cdpages%2Csv_dpages%2Cse_platform1%2Csv_platform1%2CfastStyling%2Cse_grid%2Csv_grid%2CdeveloperModeToggle&editorPlatformAppSources=%3A&viewerPlatformAppSources=%3A&WixCodeRuntimeSource=1.2216.0&EditorSource=http%3A%2F%2Flocalhost%2Feditor-base&debug=all&ReactSource=http%3A%2F%2Flocalhost&petri_ovr=specs.EnableNewRelicInSanta%3Afalse%3Bspecs.DisableNewRelicScriptsSantaEditor%3Atrue%3Bspecs.HttpsAllowedForPremiumSites%3Afalse%3Bspecs.HttpsAllowedForFreeSites%3Afalse&leavePagePopUp=false'\'
alias openviewercurrent='open '\''http://davidsu9.wixsite.com/customrouter?EditorSource=http%3A%2F%2Flocalhost%2Feditor-base&ReactSource=http%3A%2F%2Flocalhost&WixCodeRuntimeSource=1.2216.0&editorPlatformAppSources=%3A&experiments=disableDbEditorAutoSave%2CdisableSaveReminder%2CrightClickDebug%2Cdpages%2Csv_dpages%2Cse_platform1%2Csv_platform1%2CfastStyling%2Cse_grid%2Csv_grid%2CdeveloperModeToggle&petri_ovr=specs.EnableNewRelicInSanta%3Afalse%3Bspecs.DisableNewRelicScriptsSantaEditor%3Atrue%3Bspecs.HttpsAllowedForPremiumSites%3Afalse%3Bspecs.HttpsAllowedForFreeSites%3Afalse&debug=all&viewerPlatformAppSources=%3A'\'
function startdynamic(){
    (#parentheses causes code to be run in subshell
        trap "kill $(jobs -p)" SIGINT SIGTERM EXIT
        node $SV/beaker/dynamicPages/backend.js &
        cd $SV
        sudo npm start
    )
   wait
}
function startwixrichtextday(){
   {
      cd $WR &&
      git pull &&
      npm i
   }
}
function startsantaday(){
    {
        cd $SV &&
        git pull --rebase &&
        npm  i &&
        grunt all --force &&
        node tern_proj_generator `pwd`/packages > .tern-project
     } | egrep -v $LOG
}
function startsantaeditorday(){
    {
        cd ~/projects/santa-editor &&
        git pull --rebase &&
        npm i &&
        bower install --force &&
        grunt all --force &&
        node tern_proj_generator `pwd`/packages > .tern-project
    } | egrep -v $LOG
}
function startckday(){
    cd ~/projects/wix-ck-editor &&
    git pull --rebase &&
    bower update &&
    grunt all
}
function startwixcodeday(){
    cd ~/projects/js-wixcode-sdk &&
    git pull --rebase &&
    npm i &&
    grunt all &&
    npm run build &&
    cd ~/projects/santa/static/wixcode &&
    grunt &&
    cd ~/projects/santa/static/platform &&
    grunt

}
function startwixday(){
#command inside ( parenthesis ) will be run in a subshell
#allowing for parallelism
    ( startsantaday ) &
    ( startsantaeditorday ) &
    ( startckday ) &
    ( startwixrichtextday ) &
    ( startwixcodeday )
}
function notonmaster(){
    local pwd=$PWD
    cd $SV
    local currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $SE
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $CK
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $CODE_SDK
    currbranch="$(git rev-parse --abbrev-ref HEAD)"
    [[ $currbranch != "master" ]] && echo $PWD - $currbranch

    cd $pwd
}
function checkoutmasterfunc(){
    cd $1
    echo $fg[yellow]$PWD$reset_color
    git checkout master
    printf '*%.0s' {1..50}
    printf '\n\n'
}
alias checkoutmaster='checkoutmasterfunc ~/projects/wix-ck-editor && checkoutmasterfunc ~/projects/santa && checkoutmasterfunc ~/projects/santa-editor && checkoutmasterfunc ~/projects/js-wixcode-sdk'
