#!/usr/sh
function useViKeys(){
    source $HOME/.zgen/robbyrussell/oh-my-zsh-master/plugins/vi-mode/vi-mode.plugin.zsh

    #https://github.com/zsh-users/zsh-history-substring-search
    zmodload zsh/terminfo
    bindkey "${terminfo[kcuu1]}" history-substring-search-up # start typing + [Up-Arrow] - fuzzy find history forward
    bindkey "^[OB" history-substring-search-down # start typing + [Down-Arrow] - fuzzy find history backward

    #bindkey "${terminfo[kcud1]}" down-line-or-beginning-search# start typing + [Down-Arrow] - fuzzy find history backward
    #bindkey "^[OB" down-line-or-beginning-search # start typing + [Down-Arrow] - fuzzy find history backward

    bindkey -M viins "^A" beginning-of-line # Command + left arrow, insert mode
    bindkey -M vicmd "^A" beginning-of-line # Command + left arrow, command mode
    bindkey -M viins "^E" end-of-line # Command + right arrow
    bindkey -M vicmd "^E" end-of-line # Command + right arrow
    export KEYTIMEOUT=10 # http://dougblack.io/words/zsh-vi-mode.html ==> improve mode transition time - can raise issues, watch out



    #https://github.com/alx741/oh-my-zsh/blob/5f49c9c621f7e4e2a8200e6e1ea6b166b7b40f12/plugins/vi-mode/vi-mode.plugin.zsh
    #I made some changes to make it work on mac
    function useSystemClipboard(){
        function cutbuffer() {
            zle .$WIDGET
            echo $CUTBUFFER | pbcopy
        }
        zle_cut_widgets=(
            vi-backward-delete-char
            vi-change
            vi-change-eol
            vi-change-whole-line
            vi-delete
            vi-delete-char
            vi-kill-eol
            vi-substitute
            vi-yank
            vi-yank-eol
        )
        for widget in $zle_cut_widgets
        do
            zle -N $widget cutbuffer
        done

        function putbuffer() {
            zle copy-region-as-kill "$(pbpaste)"
            zle .$WIDGET
        }

        zle_put_widgets=(
            vi-put-after
            vi-put-before
        )
        for widget in $zle_put_widgets
        do
            zle -N $widget putbuffer
        done
    }
}
