#!/usr/sh
function useViKeys(){
    export KEYTIMEOUT=10 # http://dougblack.io/words/zsh-vi-mode.html ==> improve mode transition time - can raise issues, watch out
    #https://github.com/alx741/oh-my-zsh/blob/5f49c9c621f7e4e2a8200e6e1ea6b166b7b40f12/plugins/vi-mode/vi-mode.plugin.zsh
    #I made some changes to make it work on mac
    function useSystemClipboard(){
        function cutbuffer() {
            zle .$WIDGET
            echo $CUTBUFFER | pbcopy
        }
        zle_cut_widgets=(
            vi-backward-delete-char
            vi-change
            vi-change-eol
            vi-change-whole-line
            vi-delete
            vi-delete-char
            vi-kill-eol
            vi-substitute
            vi-yank
            vi-yank-eol
        )
        for widget in $zle_cut_widgets
        do
            zle -N $widget cutbuffer
        done

        function putbuffer() {
            zle copy-region-as-kill "$(pbpaste)"
            zle .$WIDGET
        }

        zle_put_widgets=(
            vi-put-after
            vi-put-before
        )
        for widget in $zle_put_widgets
        do
            zle -N $widget putbuffer
        done
    }
    useSystemClipboard
}
