#!/bin/sh
echo davidsu client hook message: post-merge has kicked in
$(nohup node ~/projects/ternProjGenerators/santa-editor.js > ~/projects/santa-editor/.tern-project & )
echo davidsu client hook message: running ternProjGenerators in the background
